apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: orderer
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: orderer0
          image: happilymarrieddadudemy/hyperledger-orderer-init-container:874079813f85762967cf1aa6bf79cd39eb8f4fab
          workingDir: /var/hyperledger/orderer
          ports:
            - containerPort: 7050
          env:
          - name: CA_SCHEME
            value: https
          - name: CA_URL
            value: "orderers-ca-service:7054"
          - name: CA_USERNAME
            value: admin
          - name: CA_PASSWORD
            value: adminpw
          volumeMounts:
            - mountPath: /fabric-ca-server
              name: my-pv-storage
              subPath: state/orderers-ca

