apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: orderer
    spec:
      containers:
        - name: orderer0
          image: happilymarrieddadudemy/hyperledger-orderer-init-container:c483b098179dfe0d7d5ee750c61e56ec82d9306e
          workingDir: /var/hyperledger/orderer
          ports:
            - containerPort: 7050
          env:
          - name: CA_SCHEME
            value: https
          - name: CA_URL
            value: "orderers-ca-service:7054"
          - name: CA_USERNAME
            value: admin
          - name: CA_PASSWORD
            value: adminpw

