apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: orderer
    spec:
      containers:
        - name: orderer0
          image: happilymarrieddadudemy/hyperledger-orderer-init-container:11cba60fc104cd91604e539705e4ee7bd23a7137
          workingDir: /var/hyperledger/orderer
          ports:
            - containerPort: 7050
          env:
          - name: CA_HOST
            value: "orderers-ca-service"
          - name: CA_PORT
            value: "7054"

