apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: orderer
    spec:
      containers:
        - name: orderer0
          image: happilymarrieddadudemy/hyperledger-orderer-init-container:8bb1a6ca9c7501786f61b2c6eda86ee8db21411b
          workingDir: /var/hyperledger/orderer
          ports:
            - containerPort: 7050
          env:
          - name: SERVICE_TO_WAIT_FOR
            value: "https://orderers-ca-service:7054/cainfo"

