apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-ca
  labels: {
    component: ibm,
    type: ca
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ibm
      type: ca
  template:
    metadata:
      labels:
        component: ibm
        type: ca
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: ibm-ca
          image: hyperledger/fabric-ca:1.5.6
          command: ["fabric-ca-server"]
          args:
            - start
            - -b
            - admin:adminpw
            - --tls.enabled
            - --csr.hosts
            - ibm-ca,ibm-ca-service,ibm-ca-service
          ports:
            - containerPort: 7054
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: my-pv-storage
              subPath: state/ibm-ca
