apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderers-ca
  labels: {
    component: orderers,
    type: ca
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderers
      type: ca
  template:
    metadata:
      labels:
        component: orderers
        type: ca
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: orderers-ca
          image: happilymarrieddadudemy/hyperledger-ca-root-mysql-container:b30ff4422adc304f67db249d498d783193e91b91
          ports:
            - containerPort: 7054
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: CA_USR
              value: "admin"
            - name: CA_PW
              value: "adminpw"
            - name: CSR_HOSTS
              value: "orderers-ca,orderers-ca-service"
            - name: DB_DATASOURCE
              value: "usr1:pass@tcp(mysql-db-service:3306)/hyperledger?parseTime=true"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: my-pv-storage
              subPath: state/orderers-ca
            - name: my-pv-storage
              mountPath: /etc/mysql
              subPath: state/mysql
