FROM hyperledger/fabric-ca:1.5.6

RUN apt update -y
RUN apt install curl jq -y

COPY ../scripts/orderers/wait_for_ca.sh /scripts/
COPY ../scripts/orderers/init_container.sh /scripts/

CMD ["/scripts/init_container.sh"]
